config/routes.rb
Rails.application.routes.draw do
  root          to: 'users#home'

  resources :users do
  	resources :messages, shallow: true, except: (:index) do
  	  resources :activities, shallow: true
  	end
  end

  get '/messages', to: 'messages#index'

  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  get     '/logout',   to: 'sessions#destroy'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  searchkick
  belongs_to :user
  has_many :activities
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :messages
  has_many :activities
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://www.sessionlogs.com/media/icons/defaultIcon.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_message, only: [:new, :create, :index]

  # GET /activities
  def index
    @activities = Activity.where(message_id: @message.id)
  end

  # GET /activities/1
  def show
    if !logged_in?
      redirect_to login_path
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new(user_id: params[:user_id])
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)
    @activity.message = @message
    @activity.user = current_user
    if @activity.save
      redirect_to activity_path(@activity)
    else
      flash[:error] = "Wrong message parameters"
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def set_message
      @message = Message.find(params[:message_id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_params
      params.require(:activity).permit(:key_verse, :review, :description, :materials, :media_ref, :grade, :user_id, :message_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  def index
    @messages = Message.all
    if params[:query].present?
      @messages = Message.search(params[:query])
    end
  end

  # GET /messages/1
  def show
    if !logged_in?
      redirect_to login_path
    end
  end

  # GET /messages/new
  def new
    @message = Message.new(user_id: params[:user_id])
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    message = message_params
    message[:user_id] = params[:user_id]
    @message = Message.new(message)
    if @message.save
      redirect_to message_path(@message)
    else
      flash[:error] = "Wrong message parameters"
      render :new
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:series, :title, :content, :costumes, :props, :featured, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
      flash[:success] = "Welcome back, #{user.first_name}!"
    else
      flash.now[:danger] = 'Invalid email/password combination' # Displays flash messages on rendered pages
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:        [:show, :edit, :update, :destroy]
  before_action :is_current_user, only: [       :edit, :update, :destroy]

  def home
  end

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find_by_id(params[:id])
    if !logged_in?
      redirect_to login_path
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "User created successfully!"
      redirect_to root_path
    else
      flash[:error] = "Not Valid Account Info"
      redirect_to login_path
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find_by_id(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    flash[:success] = "User deleted successfully"
    redirect_to root_path
  end

  private
    def is_current_user
      @user = User.find_by_id(params[:id])
      if @user != current_user
        redirect_to login_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :birthday, :phone, :grade, :image, :avatar)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #Assigns session to user - logs in
  def log_in (user)
    session[:user_id] = user.id
  end

  #Checks if user is the logged in user
  def current_user?(user)
    user == current_user
  end

  #Confirms user as signed in
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #Checks if current user is logged in
  def logged_in?
    !!current_user
  end

  #Logs out current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_for activity, method: :post, url: message_activities_path(@message, activity.id) do |f| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grade %>
    <%= f.text_field :grade, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :key_verse %>
    <%= f.text_field :key_verse, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_field :review, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :materials %>
    <%= f.text_field :materials, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :media_ref %>
    <%= f.text_field :media_ref, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'OK', class: "btn btn-default" %>
  </div>
<% end %>

app/views/activities/_form2.html.erb
<%= form_for activity, method: :put, url: activity_path(activity.id) do |f| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grade %>
    <%= f.text_field :grade, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :key_verse %>
    <%= f.text_field :key_verse, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_field :review, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :materials %>
    <%= f.text_field :materials, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :media_ref %>
    <%= f.text_field :media_ref, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'OK', class: "btn btn-default" %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form2', activity: @activity %>

<%= link_to 'Back', activity_path(@activity) %>

app/views/activities/index.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>
<%= render 'layouts/banner', user: @user %>

<% @activities.each do |activity| %>

<h4>Grade: <%=link_to "#{activity.grade}", activity_path(activity) %></h4>

<% end %>

<%= link_to 'Back', message_path(@message) %>

app/views/activities/new.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>

<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', message_path(@message) %>

app/views/activities/show.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>
<%= render 'layouts/banner', user: @user %>

<h4>Grade: <%= @activity.grade %></h4>
<h4>Key verse: <%= @activity.key_verse %></h4>
<h4>Materials: <%= @activity.materials %></h4>
<h4>Media Reference: <%= @activity.media_ref %></h4>
<h4>Review: <%= @activity.review %></h4>
<h4>Description: <%= @activity.description %></h4>

<%= link_to 'Edit', edit_activity_path(@activity) %> 

app/views/layouts/_banner.html.erb
<div class="banner">
  <img class="img-responsive" src="http://firstfamily.us/mt-content/uploads/2017/10/biblebanner.jpg">
</div>

<br>
<br>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navbar-offcanvas" data-canvas="body">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Teacher Archives</a>
  </div>
  <div class="navbar-offcanvas offcanvas">
    <a class="navmenu-brand" href="/">Teacher Archives</a>
    <ul class="nav navbar-nav">
    <% if !logged_in? %>
      <li><a href="/login">Log In</a></li>
      <li><a href="/users/new">Sign Up</a></li>
    <% end %>
    <% if logged_in? %>
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "All Messages", messages_path %></li>
      <li><a href="/logout">Log Out</a></li>
    <% end %>
    </ul>
  </div><!--/.nav-collapse -->
</div>

app/views/layouts/_spacer.html.erb
<div class="spacer"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>teacher archives</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>

    <%= csrf_meta_tags %>

    <%= favicon_link_tag "favicon.ico" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for message, url: user_messages_path(current_user.id, message.id) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :series %>
    <%= f.text_field :series, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :costumes %>
    <%= f.text_field :costumes, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :props %>
    <%= f.text_field :props, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :featured %>
    <%= f.check_box :featured, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= f.submit 'OK', class: "btn btn-default" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>

<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>
<%= render 'layouts/banner', user: @user %>

<h1>Messages</h1>

<div class='messages-search'>
  <%= form_tag messages_path, method: :get, class: "form-inline" do %>
    <div class='form-group'>
      <span><%= text_field_tag :query, params[:query], class: 'form-control' %></span>
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
      <%= link_to 'Create Message', new_user_message_path(current_user), class: "btn btn-default" %>
    </div>
  <% end %>
</div>


<% @messages.each do |message| %>
  <div>
    <h4><%=link_to "#{message.series} - #{message.title}", message_path(message) %></h4>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>

<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>
<%= render 'layouts/banner', user: @user %>

<%= link_to 'Smallgroup Activities', message_activities_path(@message), class: "btn btn-default" %>
<%= link_to 'Create Smallgroup Activity', new_message_activity_path(@message), class: "btn btn-default" %>

  <h4>Series: <%= @message.series %><h4>
  <h4>Title: <%= @message.title %><h4>
  <h4>Costumes: <%= @message.costumes %><h4>
  <h4>Props: <%= @message.props %><h4>
  <h4><%= @message.content %><h4>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %> |
<%= link_to 'Delete', message_path, method: "delete" %>

app/views/users/_form.html.erb
<%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday, start_year: Date.today.year - 17, end_year: Date.today.year - 80, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :grade %>
    <%= f.text_field :grade, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'OK', class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>


<% if !logged_in? %>
  <div class='row'>
	  <div class='col-xs-12'>
  	  <img class='img-responsive home-logo' src="http://firstfamily.us/mt-content/uploads/2017/10/biblebanner.jpg">
      <div style="margin: 0 auto; text-align: center;">
        <h1>WELCOME TO TEACHER ARCHIVES!</h1>
        <h2>A Sunday School Teachers Resource Library</h2>
      </div>
	  </div>
  </div>
<%end%>

<% if logged_in? %>
<%= render 'layouts/banner', user: @user %>

  <div>
    <div class="col-sm-6 col-md-4 col-md-offset-2">
      <div class="thumbnail">
        <img class="home" src="http://media.oregonlive.com/themombeat/photo/11449196-large.jpg" alt="messages">
        <div class="caption text-center">
          <h4><%= link_to "Messages", messages_path %></h4>
        </div>
      </div>
    </div>
  </div>

  <div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img class="home" src="https://www.sandiegounified.org/sites/default/files_link/district/files/dept/teacher_preparation_and_support_/Pictures/teacher2.jpg" alt="teachers">
        <div class="caption text-center">
          <h4><%= link_to "Teachers", users_path %></h4>
        </div>
      </div>
    </div>
  </div>

<%end%>

app/views/users/index.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>
<%= render 'layouts/banner', user: @user %>

<% @users.each do |user| %>

  <div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%if user.avatar.blank? %>
          <%= image_tag('http://www.sessionlogs.com/media/icons/defaultIcon.png') %>
        <% else %>
          <%= image_tag(user.avatar) %>
        <% end %> 
        <div class="caption text-center">
          <h4><%=link_to "Teacher " + user.first_name + " " + user.last_name, user_path(user) %></h4>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/users/new.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>

<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render 'layouts/header', user: @user %>
<%= render 'layouts/spacer', user: @user %>
<%= render 'layouts/banner', user: @user %>

<% if current_user?(@user) %>

  <div class='row'>
    <div class='profile col-xs-12 col-sm-4 col-md-4 text-center'>
      <%if current_user.avatar.blank? %>
        <%= image_tag('https://www.umass.edu/afroam/sites/default/files/store/img/cfm/user_13.png') %>
      <% else %>
        <%= image_tag(current_user.avatar) %>
      <% end %>

      <h4>
        <%= "Teacher " + current_user.first_name %>
      </h4>
    </div>
  </div>

  <div class="row"></div>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

<% else %>

  <div class='row'>
    <div class='profile col-xs-12 col-sm-4 col-md-4 text-center'>
      <%if @user.avatar.blank? %>
        <%= image_tag('https://www.umass.edu/afroam/sites/default/files/store/img/cfm/user_13.png') %>
      <% else %>
        <%= image_tag(@user.avatar) %>
      <% end %>
    </div>
  </div>

  <div class="row"></div>

  <h4>
  First name:
    <%= @user.first_name %>
  </h4>

  <h4>
  Last name:
    <%= @user.last_name %>
  </h4>

  <h4>
  Email:
    <%= @user.email %>
  </h4>

  <h4>
  Birthday:
    <%= @user.birthday %>
  </h4>

  <h4>
  Phone:
    <%= @user.phone %>
  </h4>

  <h4>
  Grade:
    <%= @user.grade %>
  </h4>

  <%= link_to 'Back', users_path %>

<% end %>